<?php

/**
 * @file
 * Contains mapbox_block.preprocess.inc.
 */

/**
 * Prepares variables for mapbox template.
 *
 * Default template: mapbox.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_mapbox(array &$variables) {
}
